name: BDSX Issue auto-closer
description: Automatically closes issues.
author: karikera
branding:
  icon: alert-circle
  color: green
inputs:
  github-token:
    description: GitHub token
runs:
  using: node12
  main: dist/index.js
